/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:58ba2983-1177-4ac9-844a-1d7924b01197",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_TPDCbaT3j",
    "aws_user_pools_web_client_id": "6u85sqg8eq3re8keduk0vljoou",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://afkar4abdrh4tpu2jztthon2ym.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-l6t7n4szqzavjosucv6i3ahgoe",
    "aws_user_files_s3_bucket": "amplifyreactgraphqlc14e067d29f046c7b5c55632c278232115-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
